//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.9.0.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


namespace AindForceForagingDataSchema.AindForceForagingTask
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.3.0.0 (Newtonsoft.Json v13.0.0.0)")]
    [Bonsai.CombinatorAttribute()]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    public partial class Block : EnvironmentStatistics
    {
    
        private System.Collections.Generic.List<Trial> _trials = new System.Collections.Generic.List<Trial>();
    
        private bool _shuffle = false;
    
        private int? _repeatCount;
    
        public Block()
        {
        }
    
        protected Block(Block other) : 
                base(other)
        {
            _trials = other._trials;
            _shuffle = other._shuffle;
            _repeatCount = other._repeatCount;
        }
    
        /// <summary>
        /// List of trials in the block
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("trials")]
        [System.ComponentModel.DescriptionAttribute("List of trials in the block")]
        public System.Collections.Generic.List<Trial> Trials
        {
            get
            {
                return _trials;
            }
            set
            {
                _trials = value;
            }
        }
    
        /// <summary>
        /// Whether to shuffle the trials in the block
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("shuffle")]
        [System.ComponentModel.DescriptionAttribute("Whether to shuffle the trials in the block")]
        public bool Shuffle
        {
            get
            {
                return _shuffle;
            }
            set
            {
                _shuffle = value;
            }
        }
    
        /// <summary>
        /// Number of times to repeat the block. If null, the block will be repeated indefinitely
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("repeat_count")]
        [System.ComponentModel.DescriptionAttribute("Number of times to repeat the block. If null, the block will be repeated indefini" +
            "tely")]
        public int? RepeatCount
        {
            get
            {
                return _repeatCount;
            }
            set
            {
                _repeatCount = value;
            }
        }
    
        public System.IObservable<Block> Process()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new Block(this)));
        }
    
        public System.IObservable<Block> Process<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new Block(this));
        }
    
        protected override bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            if (base.PrintMembers(stringBuilder))
            {
                stringBuilder.Append(", ");
            }
            stringBuilder.Append("trials = " + _trials + ", ");
            stringBuilder.Append("shuffle = " + _shuffle + ", ");
            stringBuilder.Append("repeat_count = " + _repeatCount);
            return true;
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.3.0.0 (Newtonsoft.Json v13.0.0.0)")]
    [Bonsai.CombinatorAttribute()]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    public partial class Environment
    {
    
        private System.Collections.Generic.List<EnvironmentStatistics> _blockStatistics = new System.Collections.Generic.List<EnvironmentStatistics>();
    
        private bool _shuffle = false;
    
        private int? _repeatCount;
    
        public Environment()
        {
        }
    
        protected Environment(Environment other)
        {
            _blockStatistics = other._blockStatistics;
            _shuffle = other._shuffle;
            _repeatCount = other._repeatCount;
        }
    
        /// <summary>
        /// Statistics of the environment
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("block_statistics", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("Statistics of the environment")]
        public System.Collections.Generic.List<EnvironmentStatistics> BlockStatistics
        {
            get
            {
                return _blockStatistics;
            }
            set
            {
                _blockStatistics = value;
            }
        }
    
        /// <summary>
        /// Whether to shuffle the blocks
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("shuffle")]
        [System.ComponentModel.DescriptionAttribute("Whether to shuffle the blocks")]
        public bool Shuffle
        {
            get
            {
                return _shuffle;
            }
            set
            {
                _shuffle = value;
            }
        }
    
        /// <summary>
        /// Number of times to repeat the environment. If null, the environment will be repeated indefinitely
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("repeat_count")]
        [System.ComponentModel.DescriptionAttribute("Number of times to repeat the environment. If null, the environment will be repea" +
            "ted indefinitely")]
        public int? RepeatCount
        {
            get
            {
                return _repeatCount;
            }
            set
            {
                _repeatCount = value;
            }
        }
    
        public System.IObservable<Environment> Process()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new Environment(this)));
        }
    
        public System.IObservable<Environment> Process<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new Environment(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("block_statistics = " + _blockStatistics + ", ");
            stringBuilder.Append("shuffle = " + _shuffle + ", ");
            stringBuilder.Append("repeat_count = " + _repeatCount);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.3.0.0 (Newtonsoft.Json v13.0.0.0)")]
    [Newtonsoft.Json.JsonConverter(typeof(JsonInheritanceConverter), "mode")]
    [JsonInheritanceAttribute("Block", typeof(Block))]
    [JsonInheritanceAttribute("RandomWalk", typeof(RandomWalkStatistics))]
    [Bonsai.CombinatorAttribute()]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    public partial class EnvironmentStatistics
    {
    
        public EnvironmentStatistics()
        {
        }
    
        protected EnvironmentStatistics(EnvironmentStatistics other)
        {
        }
    
        public System.IObservable<EnvironmentStatistics> Process()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new EnvironmentStatistics(this)));
        }
    
        public System.IObservable<EnvironmentStatistics> Process<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new EnvironmentStatistics(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            return false;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.3.0.0 (Newtonsoft.Json v13.0.0.0)")]
    [Newtonsoft.Json.JsonConverter(typeof(JsonInheritanceConverter), "label")]
    [JsonInheritanceAttribute("LeftHarvestAction", typeof(LeftHarvestAction))]
    [JsonInheritanceAttribute("RightHarvestAction", typeof(RightHarvestAction))]
    [Bonsai.CombinatorAttribute()]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    public partial class HarvestAction
    {
    
        public HarvestAction()
        {
        }
    
        protected HarvestAction(HarvestAction other)
        {
        }
    
        public System.IObservable<HarvestAction> Process()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new HarvestAction(this)));
        }
    
        public System.IObservable<HarvestAction> Process<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new HarvestAction(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            return false;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    /// <summary>
    /// Defines an initiation period
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.3.0.0 (Newtonsoft.Json v13.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Defines an initiation period")]
    [Bonsai.CombinatorAttribute()]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    public partial class InitiationPeriod
    {
    
        private double _duration = 0D;
    
        private bool _hasCue = true;
    
        private bool _abortOnForce = false;
    
        private double _abortOnForceThreshold = 0D;
    
        public InitiationPeriod()
        {
        }
    
        protected InitiationPeriod(InitiationPeriod other)
        {
            _duration = other._duration;
            _hasCue = other._hasCue;
            _abortOnForce = other._abortOnForce;
            _abortOnForceThreshold = other._abortOnForceThreshold;
        }
    
        /// <summary>
        /// Duration of the initiation period
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("duration")]
        [System.ComponentModel.DescriptionAttribute("Duration of the initiation period")]
        public double Duration
        {
            get
            {
                return _duration;
            }
            set
            {
                _duration = value;
            }
        }
    
        /// <summary>
        /// Whether to use a cue to signal the start of the period.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("has_cue")]
        [System.ComponentModel.DescriptionAttribute("Whether to use a cue to signal the start of the period.")]
        public bool HasCue
        {
            get
            {
                return _hasCue;
            }
            set
            {
                _hasCue = value;
            }
        }
    
        /// <summary>
        /// Whether to abort the trial if a choice is made during the initiation period.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("abort_on_force")]
        [System.ComponentModel.DescriptionAttribute("Whether to abort the trial if a choice is made during the initiation period.")]
        public bool AbortOnForce
        {
            get
            {
                return _abortOnForce;
            }
            set
            {
                _abortOnForce = value;
            }
        }
    
        /// <summary>
        /// Time out for the quiescence period
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("abort_on_force_threshold")]
        [System.ComponentModel.DescriptionAttribute("Time out for the quiescence period")]
        public double AbortOnForceThreshold
        {
            get
            {
                return _abortOnForceThreshold;
            }
            set
            {
                _abortOnForceThreshold = value;
            }
        }
    
        public System.IObservable<InitiationPeriod> Process()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new InitiationPeriod(this)));
        }
    
        public System.IObservable<InitiationPeriod> Process<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new InitiationPeriod(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("duration = " + _duration + ", ");
            stringBuilder.Append("has_cue = " + _hasCue + ", ");
            stringBuilder.Append("abort_on_force = " + _abortOnForce + ", ");
            stringBuilder.Append("abort_on_force_threshold = " + _abortOnForceThreshold);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.3.0.0 (Newtonsoft.Json v13.0.0.0)")]
    [Bonsai.CombinatorAttribute()]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    public partial class LeftHarvestAction : HarvestAction
    {
    
        private double _probability = 1D;
    
        private double _amount = 1D;
    
        private double _delay = 0D;
    
        private double _forceDuration = 0.5D;
    
        private double _forceThreshold = 5000D;
    
        public LeftHarvestAction()
        {
        }
    
        protected LeftHarvestAction(LeftHarvestAction other) : 
                base(other)
        {
            _probability = other._probability;
            _amount = other._amount;
            _delay = other._delay;
            _forceDuration = other._forceDuration;
            _forceThreshold = other._forceThreshold;
        }
    
        /// <summary>
        /// Probability of reward
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("probability")]
        [System.ComponentModel.DescriptionAttribute("Probability of reward")]
        public double Probability
        {
            get
            {
                return _probability;
            }
            set
            {
                _probability = value;
            }
        }
    
        /// <summary>
        /// Amount of reward to be delivered
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("amount")]
        [System.ComponentModel.DescriptionAttribute("Amount of reward to be delivered")]
        public double Amount
        {
            get
            {
                return _amount;
            }
            set
            {
                _amount = value;
            }
        }
    
        /// <summary>
        /// Delay between successful harvest and reward delivery
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("delay")]
        [System.ComponentModel.DescriptionAttribute("Delay between successful harvest and reward delivery")]
        public double Delay
        {
            get
            {
                return _delay;
            }
            set
            {
                _delay = value;
            }
        }
    
        /// <summary>
        /// Duration that the force much stay above threshold
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("force_duration")]
        [System.ComponentModel.DescriptionAttribute("Duration that the force much stay above threshold")]
        public double ForceDuration
        {
            get
            {
                return _forceDuration;
            }
            set
            {
                _forceDuration = value;
            }
        }
    
        /// <summary>
        /// Force to be applied
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("force_threshold")]
        [System.ComponentModel.DescriptionAttribute("Force to be applied")]
        public double ForceThreshold
        {
            get
            {
                return _forceThreshold;
            }
            set
            {
                _forceThreshold = value;
            }
        }
    
        public System.IObservable<LeftHarvestAction> Process()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new LeftHarvestAction(this)));
        }
    
        public System.IObservable<LeftHarvestAction> Process<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new LeftHarvestAction(this));
        }
    
        protected override bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            if (base.PrintMembers(stringBuilder))
            {
                stringBuilder.Append(", ");
            }
            stringBuilder.Append("probability = " + _probability + ", ");
            stringBuilder.Append("amount = " + _amount + ", ");
            stringBuilder.Append("delay = " + _delay + ", ");
            stringBuilder.Append("force_duration = " + _forceDuration + ", ");
            stringBuilder.Append("force_threshold = " + _forceThreshold);
            return true;
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.3.0.0 (Newtonsoft.Json v13.0.0.0)")]
    [Bonsai.CombinatorAttribute()]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    public partial class NumericalUpdater
    {
    
        private NumericalUpdaterOperation _operation = AindForceForagingDataSchema.AindForceForagingTask.NumericalUpdaterOperation.None;
    
        private NumericalUpdaterParameters _parameters;
    
        public NumericalUpdater()
        {
        }
    
        protected NumericalUpdater(NumericalUpdater other)
        {
            _operation = other._operation;
            _parameters = other._parameters;
        }
    
        /// <summary>
        /// Operation to perform on the parameter
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("operation")]
        [System.ComponentModel.DescriptionAttribute("Operation to perform on the parameter")]
        public NumericalUpdaterOperation Operation
        {
            get
            {
                return _operation;
            }
            set
            {
                _operation = value;
            }
        }
    
        /// <summary>
        /// Parameters of the updater
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("parameters")]
        [System.ComponentModel.DescriptionAttribute("Parameters of the updater")]
        public NumericalUpdaterParameters Parameters
        {
            get
            {
                return _parameters;
            }
            set
            {
                _parameters = value;
            }
        }
    
        public System.IObservable<NumericalUpdater> Process()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new NumericalUpdater(this)));
        }
    
        public System.IObservable<NumericalUpdater> Process<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new NumericalUpdater(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("operation = " + _operation + ", ");
            stringBuilder.Append("parameters = " + _parameters);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.3.0.0 (Newtonsoft.Json v13.0.0.0)")]
    [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
    public enum NumericalUpdaterOperation
    {
    
        [System.Runtime.Serialization.EnumMemberAttribute(Value="None")]
        None = 0,
    
        [System.Runtime.Serialization.EnumMemberAttribute(Value="Offset")]
        Offset = 1,
    
        [System.Runtime.Serialization.EnumMemberAttribute(Value="Gain")]
        Gain = 2,
    
        [System.Runtime.Serialization.EnumMemberAttribute(Value="Set")]
        Set = 3,
    
        [System.Runtime.Serialization.EnumMemberAttribute(Value="OffsetPercentage")]
        OffsetPercentage = 4,
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.3.0.0 (Newtonsoft.Json v13.0.0.0)")]
    [Bonsai.CombinatorAttribute()]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    public partial class NumericalUpdaterParameters
    {
    
        private double _initialValue = 0D;
    
        private double _increment = 0D;
    
        private double _decrement = 0D;
    
        private double _minimum = 0D;
    
        private double _maximum = 0D;
    
        public NumericalUpdaterParameters()
        {
        }
    
        protected NumericalUpdaterParameters(NumericalUpdaterParameters other)
        {
            _initialValue = other._initialValue;
            _increment = other._increment;
            _decrement = other._decrement;
            _minimum = other._minimum;
            _maximum = other._maximum;
        }
    
        /// <summary>
        /// Initial value of the parameter
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("initial_value")]
        [System.ComponentModel.DescriptionAttribute("Initial value of the parameter")]
        public double InitialValue
        {
            get
            {
                return _initialValue;
            }
            set
            {
                _initialValue = value;
            }
        }
    
        /// <summary>
        /// Value to increment the parameter by
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("increment")]
        [System.ComponentModel.DescriptionAttribute("Value to increment the parameter by")]
        public double Increment
        {
            get
            {
                return _increment;
            }
            set
            {
                _increment = value;
            }
        }
    
        /// <summary>
        /// Value to decrement the parameter by
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("decrement")]
        [System.ComponentModel.DescriptionAttribute("Value to decrement the parameter by")]
        public double Decrement
        {
            get
            {
                return _decrement;
            }
            set
            {
                _decrement = value;
            }
        }
    
        /// <summary>
        /// Minimum value of the parameter
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("minimum")]
        [System.ComponentModel.DescriptionAttribute("Minimum value of the parameter")]
        public double Minimum
        {
            get
            {
                return _minimum;
            }
            set
            {
                _minimum = value;
            }
        }
    
        /// <summary>
        /// Minimum value of the parameter
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("maximum")]
        [System.ComponentModel.DescriptionAttribute("Minimum value of the parameter")]
        public double Maximum
        {
            get
            {
                return _maximum;
            }
            set
            {
                _maximum = value;
            }
        }
    
        public System.IObservable<NumericalUpdaterParameters> Process()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new NumericalUpdaterParameters(this)));
        }
    
        public System.IObservable<NumericalUpdaterParameters> Process<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new NumericalUpdaterParameters(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("initial_value = " + _initialValue + ", ");
            stringBuilder.Append("increment = " + _increment + ", ");
            stringBuilder.Append("decrement = " + _decrement + ", ");
            stringBuilder.Append("minimum = " + _minimum + ", ");
            stringBuilder.Append("maximum = " + _maximum);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    /// <summary>
    /// Defines a quiescence settings
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.3.0.0 (Newtonsoft.Json v13.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Defines a quiescence settings")]
    [Bonsai.CombinatorAttribute()]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    public partial class QuiescencePeriod
    {
    
        private double _duration = 0D;
    
        private double _forceThreshold = 0D;
    
        private double _ditheringDuration = 0D;
    
        private bool _hasCue = false;
    
        public QuiescencePeriod()
        {
        }
    
        protected QuiescencePeriod(QuiescencePeriod other)
        {
            _duration = other._duration;
            _forceThreshold = other._forceThreshold;
            _ditheringDuration = other._ditheringDuration;
            _hasCue = other._hasCue;
        }
    
        /// <summary>
        /// Duration of the quiescence period
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("duration")]
        [System.ComponentModel.DescriptionAttribute("Duration of the quiescence period")]
        public double Duration
        {
            get
            {
                return _duration;
            }
            set
            {
                _duration = value;
            }
        }
    
        /// <summary>
        /// Time out for the quiescence period
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("force_threshold")]
        [System.ComponentModel.DescriptionAttribute("Time out for the quiescence period")]
        public double ForceThreshold
        {
            get
            {
                return _forceThreshold;
            }
            set
            {
                _forceThreshold = value;
            }
        }
    
        /// <summary>
        /// Dithering duration used to exclude sporadic fast force changes.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("dithering_duration")]
        [System.ComponentModel.DescriptionAttribute("Dithering duration used to exclude sporadic fast force changes.")]
        public double DitheringDuration
        {
            get
            {
                return _ditheringDuration;
            }
            set
            {
                _ditheringDuration = value;
            }
        }
    
        /// <summary>
        /// Whether to use a cue to signal the start of the period.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("has_cue")]
        [System.ComponentModel.DescriptionAttribute("Whether to use a cue to signal the start of the period.")]
        public bool HasCue
        {
            get
            {
                return _hasCue;
            }
            set
            {
                _hasCue = value;
            }
        }
    
        public System.IObservable<QuiescencePeriod> Process()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new QuiescencePeriod(this)));
        }
    
        public System.IObservable<QuiescencePeriod> Process<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new QuiescencePeriod(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("duration = " + _duration + ", ");
            stringBuilder.Append("force_threshold = " + _forceThreshold + ", ");
            stringBuilder.Append("dithering_duration = " + _ditheringDuration + ", ");
            stringBuilder.Append("has_cue = " + _hasCue);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.3.0.0 (Newtonsoft.Json v13.0.0.0)")]
    [Bonsai.CombinatorAttribute()]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    public partial class RandomWalkStatistics : EnvironmentStatistics
    {
    
        public RandomWalkStatistics()
        {
        }
    
        protected RandomWalkStatistics(RandomWalkStatistics other) : 
                base(other)
        {
        }
    
        public System.IObservable<RandomWalkStatistics> Process()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new RandomWalkStatistics(this)));
        }
    
        public System.IObservable<RandomWalkStatistics> Process<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new RandomWalkStatistics(this));
        }
    
        protected override bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            return base.PrintMembers(stringBuilder);
        }
    }


    /// <summary>
    /// Defines a response period
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.3.0.0 (Newtonsoft.Json v13.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Defines a response period")]
    [Bonsai.CombinatorAttribute()]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    public partial class ResponsePeriod
    {
    
        private double _duration = 0D;
    
        private bool _hasCue = true;
    
        private bool _abortOnForce = false;
    
        private double _abortOnForceThreshold = 0D;
    
        private bool _hasFeedback = false;
    
        public ResponsePeriod()
        {
        }
    
        protected ResponsePeriod(ResponsePeriod other)
        {
            _duration = other._duration;
            _hasCue = other._hasCue;
            _abortOnForce = other._abortOnForce;
            _abortOnForceThreshold = other._abortOnForceThreshold;
            _hasFeedback = other._hasFeedback;
        }
    
        /// <summary>
        /// Duration of the response period. I.e. the time the animal has to make a choice.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("duration")]
        [System.ComponentModel.DescriptionAttribute("Duration of the response period. I.e. the time the animal has to make a choice.")]
        public double Duration
        {
            get
            {
                return _duration;
            }
            set
            {
                _duration = value;
            }
        }
    
        /// <summary>
        /// Whether to use a cue to signal the start of the period.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("has_cue")]
        [System.ComponentModel.DescriptionAttribute("Whether to use a cue to signal the start of the period.")]
        public bool HasCue
        {
            get
            {
                return _hasCue;
            }
            set
            {
                _hasCue = value;
            }
        }
    
        /// <summary>
        /// Whether to abort the trial if a choice is made during the initiation period.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("abort_on_force")]
        [System.ComponentModel.DescriptionAttribute("Whether to abort the trial if a choice is made during the initiation period.")]
        public bool AbortOnForce
        {
            get
            {
                return _abortOnForce;
            }
            set
            {
                _abortOnForce = value;
            }
        }
    
        /// <summary>
        /// Time out for the quiescence period
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("abort_on_force_threshold")]
        [System.ComponentModel.DescriptionAttribute("Time out for the quiescence period")]
        public double AbortOnForceThreshold
        {
            get
            {
                return _abortOnForceThreshold;
            }
            set
            {
                _abortOnForceThreshold = value;
            }
        }
    
        /// <summary>
        /// Whether to provide feedback to the animal after the response period.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("has_feedback")]
        [System.ComponentModel.DescriptionAttribute("Whether to provide feedback to the animal after the response period.")]
        public bool HasFeedback
        {
            get
            {
                return _hasFeedback;
            }
            set
            {
                _hasFeedback = value;
            }
        }
    
        public System.IObservable<ResponsePeriod> Process()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new ResponsePeriod(this)));
        }
    
        public System.IObservable<ResponsePeriod> Process<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new ResponsePeriod(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("duration = " + _duration + ", ");
            stringBuilder.Append("has_cue = " + _hasCue + ", ");
            stringBuilder.Append("abort_on_force = " + _abortOnForce + ", ");
            stringBuilder.Append("abort_on_force_threshold = " + _abortOnForceThreshold + ", ");
            stringBuilder.Append("has_feedback = " + _hasFeedback);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    /// <summary>
    /// Defines a reward period
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.3.0.0 (Newtonsoft.Json v13.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Defines a reward period")]
    [Bonsai.CombinatorAttribute()]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    public partial class RewardPeriod
    {
    
        private double _delay = 0D;
    
        private bool _isOperant = true;
    
        private bool _hasCue = true;
    
        private double? _timeToCollect;
    
        public RewardPeriod()
        {
        }
    
        protected RewardPeriod(RewardPeriod other)
        {
            _delay = other._delay;
            _isOperant = other._isOperant;
            _hasCue = other._hasCue;
            _timeToCollect = other._timeToCollect;
        }
    
        /// <summary>
        /// Delay to reward availability.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("delay")]
        [System.ComponentModel.DescriptionAttribute("Delay to reward availability.")]
        public double Delay
        {
            get
            {
                return _delay;
            }
            set
            {
                _delay = value;
            }
        }
    
        /// <summary>
        /// Whether the reward delivery is contingent on licking.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("is_operant")]
        [System.ComponentModel.DescriptionAttribute("Whether the reward delivery is contingent on licking.")]
        public bool IsOperant
        {
            get
            {
                return _isOperant;
            }
            set
            {
                _isOperant = value;
            }
        }
    
        /// <summary>
        /// Whether to use a cue to signal the availability of the reward.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("has_cue")]
        [System.ComponentModel.DescriptionAttribute("Whether to use a cue to signal the availability of the reward.")]
        public bool HasCue
        {
            get
            {
                return _hasCue;
            }
            set
            {
                _hasCue = value;
            }
        }
    
        /// <summary>
        /// Time to collect the reward after it is available. If null, the reward will be available indefinitely.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("time_to_collect")]
        [System.ComponentModel.DescriptionAttribute("Time to collect the reward after it is available. If null, the reward will be ava" +
            "ilable indefinitely.")]
        public double? TimeToCollect
        {
            get
            {
                return _timeToCollect;
            }
            set
            {
                _timeToCollect = value;
            }
        }
    
        public System.IObservable<RewardPeriod> Process()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new RewardPeriod(this)));
        }
    
        public System.IObservable<RewardPeriod> Process<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new RewardPeriod(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("delay = " + _delay + ", ");
            stringBuilder.Append("is_operant = " + _isOperant + ", ");
            stringBuilder.Append("has_cue = " + _hasCue + ", ");
            stringBuilder.Append("time_to_collect = " + _timeToCollect);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.3.0.0 (Newtonsoft.Json v13.0.0.0)")]
    [Bonsai.CombinatorAttribute()]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    public partial class RightHarvestAction : HarvestAction
    {
    
        private double _probability = 1D;
    
        private double _amount = 1D;
    
        private double _delay = 0D;
    
        private double _forceDuration = 0.5D;
    
        private double _forceThreshold = 5000D;
    
        public RightHarvestAction()
        {
        }
    
        protected RightHarvestAction(RightHarvestAction other) : 
                base(other)
        {
            _probability = other._probability;
            _amount = other._amount;
            _delay = other._delay;
            _forceDuration = other._forceDuration;
            _forceThreshold = other._forceThreshold;
        }
    
        /// <summary>
        /// Probability of reward
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("probability")]
        [System.ComponentModel.DescriptionAttribute("Probability of reward")]
        public double Probability
        {
            get
            {
                return _probability;
            }
            set
            {
                _probability = value;
            }
        }
    
        /// <summary>
        /// Amount of reward to be delivered
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("amount")]
        [System.ComponentModel.DescriptionAttribute("Amount of reward to be delivered")]
        public double Amount
        {
            get
            {
                return _amount;
            }
            set
            {
                _amount = value;
            }
        }
    
        /// <summary>
        /// Delay between successful harvest and reward delivery
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("delay")]
        [System.ComponentModel.DescriptionAttribute("Delay between successful harvest and reward delivery")]
        public double Delay
        {
            get
            {
                return _delay;
            }
            set
            {
                _delay = value;
            }
        }
    
        /// <summary>
        /// Duration that the force much stay above threshold
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("force_duration")]
        [System.ComponentModel.DescriptionAttribute("Duration that the force much stay above threshold")]
        public double ForceDuration
        {
            get
            {
                return _forceDuration;
            }
            set
            {
                _forceDuration = value;
            }
        }
    
        /// <summary>
        /// Force to be applied
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("force_threshold")]
        [System.ComponentModel.DescriptionAttribute("Force to be applied")]
        public double ForceThreshold
        {
            get
            {
                return _forceThreshold;
            }
            set
            {
                _forceThreshold = value;
            }
        }
    
        public System.IObservable<RightHarvestAction> Process()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new RightHarvestAction(this)));
        }
    
        public System.IObservable<RightHarvestAction> Process<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new RightHarvestAction(this));
        }
    
        protected override bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            if (base.PrintMembers(stringBuilder))
            {
                stringBuilder.Append(", ");
            }
            stringBuilder.Append("probability = " + _probability + ", ");
            stringBuilder.Append("amount = " + _amount + ", ");
            stringBuilder.Append("delay = " + _delay + ", ");
            stringBuilder.Append("force_duration = " + _forceDuration + ", ");
            stringBuilder.Append("force_threshold = " + _forceThreshold);
            return true;
        }
    }


    /// <summary>
    /// Defines a trial
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.3.0.0 (Newtonsoft.Json v13.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Defines a trial")]
    [Bonsai.CombinatorAttribute()]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    public partial class Trial
    {
    
        private double _interTrialInterval = 0D;
    
        private QuiescencePeriod _quiescencePeriod;
    
        private InitiationPeriod _initiationPeriod;
    
        private ResponsePeriod _responsePeriod;
    
        private RewardPeriod _rewardPeriod;
    
        private HarvestAction _leftAction;
    
        private HarvestAction _rightAction;
    
        private double _timeOut = 0D;
    
        public Trial()
        {
        }
    
        protected Trial(Trial other)
        {
            _interTrialInterval = other._interTrialInterval;
            _quiescencePeriod = other._quiescencePeriod;
            _initiationPeriod = other._initiationPeriod;
            _responsePeriod = other._responsePeriod;
            _rewardPeriod = other._rewardPeriod;
            _leftAction = other._leftAction;
            _rightAction = other._rightAction;
            _timeOut = other._timeOut;
        }
    
        /// <summary>
        /// Time between trials
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("inter_trial_interval")]
        [System.ComponentModel.DescriptionAttribute("Time between trials")]
        public double InterTrialInterval
        {
            get
            {
                return _interTrialInterval;
            }
            set
            {
                _interTrialInterval = value;
            }
        }
    
        /// <summary>
        /// Quiescence settings
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("quiescence_period")]
        [System.ComponentModel.DescriptionAttribute("Quiescence settings")]
        public QuiescencePeriod QuiescencePeriod
        {
            get
            {
                return _quiescencePeriod;
            }
            set
            {
                _quiescencePeriod = value;
            }
        }
    
        /// <summary>
        /// Initiation settings
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("initiation_period")]
        [System.ComponentModel.DescriptionAttribute("Initiation settings")]
        public InitiationPeriod InitiationPeriod
        {
            get
            {
                return _initiationPeriod;
            }
            set
            {
                _initiationPeriod = value;
            }
        }
    
        /// <summary>
        /// Response settings
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("response_period")]
        [System.ComponentModel.DescriptionAttribute("Response settings")]
        public ResponsePeriod ResponsePeriod
        {
            get
            {
                return _responsePeriod;
            }
            set
            {
                _responsePeriod = value;
            }
        }
    
        /// <summary>
        /// Reward settings
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("reward_period")]
        [System.ComponentModel.DescriptionAttribute("Reward settings")]
        public RewardPeriod RewardPeriod
        {
            get
            {
                return _rewardPeriod;
            }
            set
            {
                _rewardPeriod = value;
            }
        }
    
        /// <summary>
        /// Specification of the left action
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("left_action")]
        [System.ComponentModel.DescriptionAttribute("Specification of the left action")]
        public HarvestAction LeftAction
        {
            get
            {
                return _leftAction;
            }
            set
            {
                _leftAction = value;
            }
        }
    
        /// <summary>
        /// Specification of the right action
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("right_action")]
        [System.ComponentModel.DescriptionAttribute("Specification of the right action")]
        public HarvestAction RightAction
        {
            get
            {
                return _rightAction;
            }
            set
            {
                _rightAction = value;
            }
        }
    
        /// <summary>
        /// Time out for the trial
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("time_out")]
        [System.ComponentModel.DescriptionAttribute("Time out for the trial")]
        public double TimeOut
        {
            get
            {
                return _timeOut;
            }
            set
            {
                _timeOut = value;
            }
        }
    
        public System.IObservable<Trial> Process()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new Trial(this)));
        }
    
        public System.IObservable<Trial> Process<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new Trial(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("inter_trial_interval = " + _interTrialInterval + ", ");
            stringBuilder.Append("quiescence_period = " + _quiescencePeriod + ", ");
            stringBuilder.Append("initiation_period = " + _initiationPeriod + ", ");
            stringBuilder.Append("response_period = " + _responsePeriod + ", ");
            stringBuilder.Append("reward_period = " + _rewardPeriod + ", ");
            stringBuilder.Append("left_action = " + _leftAction + ", ");
            stringBuilder.Append("right_action = " + _rightAction + ", ");
            stringBuilder.Append("time_out = " + _timeOut);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.3.0.0 (Newtonsoft.Json v13.0.0.0)")]
    [Bonsai.CombinatorAttribute()]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    public partial class AindForceForagingTaskLogic
    {
    
        private string _describedBy = "";
    
        private string _schemaVersion = "0.1.0-preview01";
    
        private Environment _environment = new Environment();
    
        private System.Collections.Generic.IDictionary<string, NumericalUpdater> _updaters;
    
        public AindForceForagingTaskLogic()
        {
        }
    
        protected AindForceForagingTaskLogic(AindForceForagingTaskLogic other)
        {
            _describedBy = other._describedBy;
            _schemaVersion = other._schemaVersion;
            _environment = other._environment;
            _updaters = other._updaters;
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("describedBy")]
        public string DescribedBy
        {
            get
            {
                return _describedBy;
            }
            set
            {
                _describedBy = value;
            }
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("schema_version")]
        public string SchemaVersion
        {
            get
            {
                return _schemaVersion;
            }
            set
            {
                _schemaVersion = value;
            }
        }
    
        /// <summary>
        /// Environment settings
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("environment", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("Environment settings")]
        public Environment Environment
        {
            get
            {
                return _environment;
            }
            set
            {
                _environment = value;
            }
        }
    
        /// <summary>
        /// List of numerical updaters
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("updaters")]
        [System.ComponentModel.DescriptionAttribute("List of numerical updaters")]
        public System.Collections.Generic.IDictionary<string, NumericalUpdater> Updaters
        {
            get
            {
                return _updaters;
            }
            set
            {
                _updaters = value;
            }
        }
    
        public System.IObservable<AindForceForagingTaskLogic> Process()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new AindForceForagingTaskLogic(this)));
        }
    
        public System.IObservable<AindForceForagingTaskLogic> Process<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new AindForceForagingTaskLogic(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("describedBy = " + _describedBy + ", ");
            stringBuilder.Append("schema_version = " + _schemaVersion + ", ");
            stringBuilder.Append("environment = " + _environment + ", ");
            stringBuilder.Append("updaters = " + _updaters);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.9.0.0 (Newtonsoft.Json v13.0.0.0)")]
    [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Interface, AllowMultiple = true)]
    internal class JsonInheritanceAttribute : System.Attribute
    {
        public JsonInheritanceAttribute(string key, System.Type type)
        {
            Key = key;
            Type = type;
        }

        public string Key { get; private set; }

        public System.Type Type { get; private set; }
    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.9.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public class JsonInheritanceConverter : Newtonsoft.Json.JsonConverter
    {
        internal static readonly string DefaultDiscriminatorName = "discriminator";

        private readonly string _discriminatorName;

        [System.ThreadStatic]
        private static bool _isReading;

        [System.ThreadStatic]
        private static bool _isWriting;

        public JsonInheritanceConverter()
        {
            _discriminatorName = DefaultDiscriminatorName;
        }

        public JsonInheritanceConverter(string discriminatorName)
        {
            _discriminatorName = discriminatorName;
        }

        public string DiscriminatorName { get { return _discriminatorName; } }

        public override void WriteJson(Newtonsoft.Json.JsonWriter writer, object value, Newtonsoft.Json.JsonSerializer serializer)
        {
            try
            {
                _isWriting = true;

                var jObject = Newtonsoft.Json.Linq.JObject.FromObject(value, serializer);
                jObject.AddFirst(new Newtonsoft.Json.Linq.JProperty(_discriminatorName, GetSubtypeDiscriminator(value.GetType())));
                writer.WriteToken(jObject.CreateReader());
            }
            finally
            {
                _isWriting = false;
            }
        }

        public override bool CanWrite
        {
            get
            {
                if (_isWriting)
                {
                    _isWriting = false;
                    return false;
                }
                return true;
            }
        }

        public override bool CanRead
        {
            get
            {
                if (_isReading)
                {
                    _isReading = false;
                    return false;
                }
                return true;
            }
        }

        public override bool CanConvert(System.Type objectType)
        {
            return true;
        }

        public override object ReadJson(Newtonsoft.Json.JsonReader reader, System.Type objectType, object existingValue, Newtonsoft.Json.JsonSerializer serializer)
        {
            var jObject = serializer.Deserialize<Newtonsoft.Json.Linq.JObject>(reader);
            if (jObject == null)
                return null;

            var discriminatorValue = jObject.GetValue(_discriminatorName);
            var discriminator = discriminatorValue != null ? Newtonsoft.Json.Linq.Extensions.Value<string>(discriminatorValue) : null;
            var subtype = GetObjectSubtype(objectType, discriminator);

            var objectContract = serializer.ContractResolver.ResolveContract(subtype) as Newtonsoft.Json.Serialization.JsonObjectContract;
            if (objectContract == null || System.Linq.Enumerable.All(objectContract.Properties, p => p.PropertyName != _discriminatorName))
            {
                jObject.Remove(_discriminatorName);
            }

            try
            {
                _isReading = true;
                return serializer.Deserialize(jObject.CreateReader(), subtype);
            }
            finally
            {
                _isReading = false;
            }
        }

        private System.Type GetObjectSubtype(System.Type objectType, string discriminator)
        {
            foreach (var attribute in System.Reflection.CustomAttributeExtensions.GetCustomAttributes<JsonInheritanceAttribute>(System.Reflection.IntrospectionExtensions.GetTypeInfo(objectType), true))
            {
                if (attribute.Key == discriminator)
                    return attribute.Type;
            }

            return objectType;
        }

        private string GetSubtypeDiscriminator(System.Type objectType)
        {
            foreach (var attribute in System.Reflection.CustomAttributeExtensions.GetCustomAttributes<JsonInheritanceAttribute>(System.Reflection.IntrospectionExtensions.GetTypeInfo(objectType), true))
            {
                if (attribute.Type == objectType)
                    return attribute.Key;
            }

            return objectType.Name;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.3.0.0 (Newtonsoft.Json v13.0.0.0)")]
    [System.ComponentModel.DefaultPropertyAttribute("Type")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Combinator)]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Block>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<RandomWalkStatistics>))]
    public partial class MatchEnvironmentStatistics : Bonsai.Expressions.SingleArgumentExpressionBuilder
    {
    
        public Bonsai.Expressions.TypeMapping Type { get; set; }

        public override System.Linq.Expressions.Expression Build(System.Collections.Generic.IEnumerable<System.Linq.Expressions.Expression> arguments)
        {
            var typeMapping = Type;
            var returnType = typeMapping != null ? typeMapping.GetType().GetGenericArguments()[0] : typeof(EnvironmentStatistics);
            return System.Linq.Expressions.Expression.Call(
                typeof(MatchEnvironmentStatistics),
                "Process",
                new System.Type[] { returnType },
                System.Linq.Enumerable.Single(arguments));
        }

    
        private static System.IObservable<TResult> Process<TResult>(System.IObservable<EnvironmentStatistics> source)
            where TResult : EnvironmentStatistics
        {
            return System.Reactive.Linq.Observable.Create<TResult>(observer =>
            {
                var sourceObserver = System.Reactive.Observer.Create<EnvironmentStatistics>(
                    value =>
                    {
                        var match = value as TResult;
                        if (match != null) observer.OnNext(match);
                    },
                    observer.OnError,
                    observer.OnCompleted);
                return System.ObservableExtensions.SubscribeSafe(source, sourceObserver);
            });
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.3.0.0 (Newtonsoft.Json v13.0.0.0)")]
    [System.ComponentModel.DefaultPropertyAttribute("Type")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Combinator)]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<LeftHarvestAction>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<RightHarvestAction>))]
    public partial class MatchHarvestAction : Bonsai.Expressions.SingleArgumentExpressionBuilder
    {
    
        public Bonsai.Expressions.TypeMapping Type { get; set; }

        public override System.Linq.Expressions.Expression Build(System.Collections.Generic.IEnumerable<System.Linq.Expressions.Expression> arguments)
        {
            var typeMapping = Type;
            var returnType = typeMapping != null ? typeMapping.GetType().GetGenericArguments()[0] : typeof(HarvestAction);
            return System.Linq.Expressions.Expression.Call(
                typeof(MatchHarvestAction),
                "Process",
                new System.Type[] { returnType },
                System.Linq.Enumerable.Single(arguments));
        }

    
        private static System.IObservable<TResult> Process<TResult>(System.IObservable<HarvestAction> source)
            where TResult : HarvestAction
        {
            return System.Reactive.Linq.Observable.Create<TResult>(observer =>
            {
                var sourceObserver = System.Reactive.Observer.Create<HarvestAction>(
                    value =>
                    {
                        var match = value as TResult;
                        if (match != null) observer.OnNext(match);
                    },
                    observer.OnError,
                    observer.OnCompleted);
                return System.ObservableExtensions.SubscribeSafe(source, sourceObserver);
            });
        }
    }


    /// <summary>
    /// Serializes a sequence of data model objects into JSON strings.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.3.0.0 (Newtonsoft.Json v13.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Serializes a sequence of data model objects into JSON strings.")]
    [Bonsai.CombinatorAttribute()]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Transform)]
    public partial class SerializeToJson
    {
    
        private System.IObservable<string> Process<T>(System.IObservable<T> source)
        {
            return System.Reactive.Linq.Observable.Select(source, value => Newtonsoft.Json.JsonConvert.SerializeObject(value));
        }

        public System.IObservable<string> Process(System.IObservable<Block> source)
        {
            return Process<Block>(source);
        }

        public System.IObservable<string> Process(System.IObservable<Environment> source)
        {
            return Process<Environment>(source);
        }

        public System.IObservable<string> Process(System.IObservable<EnvironmentStatistics> source)
        {
            return Process<EnvironmentStatistics>(source);
        }

        public System.IObservable<string> Process(System.IObservable<HarvestAction> source)
        {
            return Process<HarvestAction>(source);
        }

        public System.IObservable<string> Process(System.IObservable<InitiationPeriod> source)
        {
            return Process<InitiationPeriod>(source);
        }

        public System.IObservable<string> Process(System.IObservable<LeftHarvestAction> source)
        {
            return Process<LeftHarvestAction>(source);
        }

        public System.IObservable<string> Process(System.IObservable<NumericalUpdater> source)
        {
            return Process<NumericalUpdater>(source);
        }

        public System.IObservable<string> Process(System.IObservable<NumericalUpdaterParameters> source)
        {
            return Process<NumericalUpdaterParameters>(source);
        }

        public System.IObservable<string> Process(System.IObservable<QuiescencePeriod> source)
        {
            return Process<QuiescencePeriod>(source);
        }

        public System.IObservable<string> Process(System.IObservable<RandomWalkStatistics> source)
        {
            return Process<RandomWalkStatistics>(source);
        }

        public System.IObservable<string> Process(System.IObservable<ResponsePeriod> source)
        {
            return Process<ResponsePeriod>(source);
        }

        public System.IObservable<string> Process(System.IObservable<RewardPeriod> source)
        {
            return Process<RewardPeriod>(source);
        }

        public System.IObservable<string> Process(System.IObservable<RightHarvestAction> source)
        {
            return Process<RightHarvestAction>(source);
        }

        public System.IObservable<string> Process(System.IObservable<Trial> source)
        {
            return Process<Trial>(source);
        }

        public System.IObservable<string> Process(System.IObservable<AindForceForagingTaskLogic> source)
        {
            return Process<AindForceForagingTaskLogic>(source);
        }
    }


    /// <summary>
    /// Deserializes a sequence of JSON strings into data model objects.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.3.0.0 (Newtonsoft.Json v13.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Deserializes a sequence of JSON strings into data model objects.")]
    [System.ComponentModel.DefaultPropertyAttribute("Type")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Transform)]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Block>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Environment>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<EnvironmentStatistics>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<HarvestAction>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<InitiationPeriod>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<LeftHarvestAction>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<NumericalUpdater>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<NumericalUpdaterParameters>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<QuiescencePeriod>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<RandomWalkStatistics>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<ResponsePeriod>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<RewardPeriod>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<RightHarvestAction>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Trial>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<AindForceForagingTaskLogic>))]
    public partial class DeserializeFromJson : Bonsai.Expressions.SingleArgumentExpressionBuilder
    {
    
        public DeserializeFromJson()
        {
            Type = new Bonsai.Expressions.TypeMapping<AindForceForagingTaskLogic>();
        }

        public Bonsai.Expressions.TypeMapping Type { get; set; }

        public override System.Linq.Expressions.Expression Build(System.Collections.Generic.IEnumerable<System.Linq.Expressions.Expression> arguments)
        {
            var typeMapping = (Bonsai.Expressions.TypeMapping)Type;
            var returnType = typeMapping.GetType().GetGenericArguments()[0];
            return System.Linq.Expressions.Expression.Call(
                typeof(DeserializeFromJson),
                "Process",
                new System.Type[] { returnType },
                System.Linq.Enumerable.Single(arguments));
        }

        private static System.IObservable<T> Process<T>(System.IObservable<string> source)
        {
            return System.Reactive.Linq.Observable.Select(source, value => Newtonsoft.Json.JsonConvert.DeserializeObject<T>(value));
        }
    }
}